# Project Name
TARGET = daisy

# Sources
CPP_SOURCES = daisy.cpp

# Target hardware
C_DEFS = -DPOD

# Put the program in external QSPI (8MB)
APP_TYPE = BOOT_QSPI

LIBDAISY_DIR = ../../lib/libDaisy/
DAISYSP_DIR = ../../lib/DaisySP/
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile