#!/usr/bin/env python3
"""Export a deterministic model snapshot and golden I/O for the Daisy baseline."""

from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path

import torch


ROOT = Path(__file__).resolve().parent
SEED_PROTOTYPE_DIR = ROOT / "seed_prototype"
HEADER_PATH = SEED_PROTOTYPE_DIR / "generated_model_data.h"
DEFAULT_CHECKPOINT = ROOT / "checkpoints_temporal" / "best_model.pt"

MODEL_SEED = 42
RANDOM_CASE_SEED = 43


def parse_args():
    parser = argparse.ArgumentParser(
        description="Export trained model weights and golden I/O for the Daisy baseline"
    )
    parser.add_argument(
        "--checkpoint",
        type=Path,
        default=DEFAULT_CHECKPOINT,
        help="Path to the checkpoint to export. Defaults to checkpoints_temporal/best_model.pt",
    )
    return parser.parse_args()


def sanitize_name(name: str) -> str:
    name = name.lower()
    name = re.sub(r"[^a-z0-9]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return f"g_{name}"


def format_float(value: float) -> str:
    if math.isnan(value):
        return "NAN"
    if math.isinf(value):
        return "INFINITY" if value > 0 else "-INFINITY"
    text = f"{value:.9e}f"
    if text == "-0.000000000e+00f":
        return "0.000000000e+00f"
    return text


def emit_float_array(lines: list[str], name: str, tensor: torch.Tensor, shape_comment: bool = True) -> None:
    flat = tensor.detach().cpu().contiguous().view(-1).tolist()
    if shape_comment:
        lines.append(f"// {name}: shape={tuple(tensor.shape)}")
    lines.append(f"alignas(16) static const float {name}[{len(flat)}] = {{")
    row = []

    for idx, value in enumerate(flat, start=1):
        row.append(format_float(float(value)))
        if len(row) == 6 or idx == len(flat):
            suffix = "," if idx != len(flat) else ""
            lines.append("    " + ", ".join(row) + suffix)
            row = []

    lines.append("};")
    lines.append("")


def emit_case_array(lines: list[str], base_name: str, tensor: torch.Tensor, label: str) -> None:
    emit_float_array(lines, f"{base_name}_{label}", tensor, shape_comment=False)


def load_checkpoint_weights(model: torch.nn.Module, checkpoint_path: Path) -> dict:
    if not checkpoint_path.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    payload = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    state_dict = payload["model"] if isinstance(payload, dict) and "model" in payload else payload
    model.load_state_dict(state_dict)
    return payload 


def main() -> None:
    args = parse_args()
    sys.path.insert(0, str(ROOT))
    from model import (
        CONTEXT_FRAMES,
        FRAME_SIZE,
        HOP_SIZE,
        N_FFT,
        N_FREQ_BINS,
        PolyphonicGuitarToPianoTemporal,
        SAMPLE_RATE,
    )

    torch.manual_seed(MODEL_SEED)
    model = PolyphonicGuitarToPianoTemporal()
    checkpoint = load_checkpoint_weights(model, args.checkpoint.resolve())
    model.eval()

    # Test cases: Zero input, impulse, random. Compared with MCU NN outputs.
    cases = []
    zero = torch.zeros(1, CONTEXT_FRAMES, FRAME_SIZE, dtype=torch.float32)
    cases.append(("case_zero", zero))

    impulse = torch.zeros(1, CONTEXT_FRAMES, FRAME_SIZE, dtype=torch.float32)
    impulse[0, CONTEXT_FRAMES - 1, FRAME_SIZE // 2] = 1.0
    cases.append(("case_impulse", impulse))

    gen = torch.Generator().manual_seed(RANDOM_CASE_SEED)
    random_case = 0.15 * torch.randn((1, CONTEXT_FRAMES, FRAME_SIZE), generator=gen, dtype=torch.float32)
    random_case = torch.clamp(random_case, -1.0, 1.0)
    cases.append(("case_random", random_case))

    outputs = {}
    with torch.no_grad():
        for name, case in cases:
            outputs[name] = model.infer_frame(case).squeeze(0).cpu()

    state = model.state_dict()
    param_tensors = {k: v for k, v in state.items() if k != "window"}
    param_count = sum(t.numel() for t in param_tensors.values())
    weight_bytes = sum(t.numel() * t.element_size() for t in param_tensors.values())

    lines = []
    lines.append("// Auto-generated by export_seed_baseline.py. Do not edit by hand.")
    
    if "epoch" in checkpoint:
        lines.append(f"// Checkpoint epoch: {checkpoint['epoch']}")
    if "val_loss" in checkpoint:
        lines.append(f"// Checkpoint val_loss: {checkpoint['val_loss']}")

    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append(f"static constexpr int kModelSeed = {MODEL_SEED};")
    lines.append(f"static constexpr int kCaseRandomSeed = {RANDOM_CASE_SEED};")
    lines.append(f"static constexpr int kSampleRate = {SAMPLE_RATE};")
    lines.append(f"static constexpr int kFrameSize = {FRAME_SIZE};")
    lines.append(f"static constexpr int kHopSize = {HOP_SIZE};")
    lines.append(f"static constexpr int kContextFrames = {CONTEXT_FRAMES};")
    lines.append(f"static constexpr int kFftSize = {N_FFT};")
    lines.append(f"static constexpr int kFreqBins = {N_FREQ_BINS};")
    lines.append("static constexpr int kStftFrames = 5;")
    lines.append("static constexpr int kFeatureChannels = 9;")
    lines.append("static constexpr int kBaseChannels = 32;")
    lines.append(f"static constexpr std::size_t kParameterCount = {param_count}u;")
    lines.append(f"static constexpr std::size_t kWeightBytes = {weight_bytes}u;")
    lines.append("")

    emit_float_array(lines, "g_window", state["window"])

    for key, tensor in state.items():
        if key == "window":
            continue
        emit_float_array(lines, sanitize_name(key), tensor)

    for name, case in cases:
        emit_case_array(lines, name, case.squeeze(0), "input")
        emit_case_array(lines, name, outputs[name], "golden")

    lines.append("")

    HEADER_PATH.write_text("\n".join(lines))
    print(f"Wrote {HEADER_PATH}")


if __name__ == "__main__":
    main()
