# Project Name
TARGET = Benchmarking

# Sources
CPP_SOURCES = daisy_benchmark.cpp

# Needed for reverb
USE_DAISYSP_LGPL = 1

# Library Locations
LIBDAISY_DIR = ../lib/libDaisy
DAISYSP_DIR = ../lib/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
