#!/usr/bin/env python3
"""
Fixes the export_c_header function in the training script:
the original only exported layers 0, 1, 2 but OnsetNet has 5 conv layers.
This script loads a checkpoint and re-exports a complete onset_weights.h.

Usage:
    python export_onset_header.py \
        --ckpt stage1_dist_finetune_v7/onset_best.pt \
        --metadata dataset/metadata.json \
        --out Source/onset_weights.h
"""

import argparse
import json
import os
import math
import torch


def note_name_to_midi(name: str):
    if not name or not isinstance(name, str):
        return None
    s = name.strip().replace("♯", "#").replace("♭", "b")
    pitch_map = {
        "C": 0, "C#": 1, "Db": 1, "D": 2, "D#": 3, "Eb": 3,
        "E": 4, "F": 5, "F#": 6, "Gb": 6, "G": 7, "G#": 8, "Ab": 8,
        "A": 9, "A#": 10, "Bb": 10, "B": 11,
    }
    if len(s) >= 3 and s[1] in ["#", "b"]:
        pc, octv = s[:2], s[2:]
    else:
        pc, octv = s[:1], s[1:]
    if pc not in pitch_map:
        return None
    try:
        octave = int(octv)
    except ValueError:
        return None
    return (octave + 1) * 12 + pitch_map[pc]


def ascii_pitch(p: str) -> str:
    return p.replace("♯", "#").replace("♭", "b")


def arr(name: str, t: "torch.Tensor") -> list[str]:
    """Format a tensor as a C float array."""
    flat = t.detach().cpu().float().numpy().flatten()
    # Write 8 values per line for readability
    vals_per_line = 8
    lines = [f"// shape: {list(t.shape)}", f"static const float {name}[{len(flat)}] = {{"]
    for i in range(0, len(flat), vals_per_line):
        chunk = flat[i:i + vals_per_line]
        line = "    " + ", ".join(f"{v:.8f}f" for v in chunk)
        if i + vals_per_line < len(flat):
            line += ","
        lines.append(line)
    lines += ["};", ""]
    return lines


def export_full_header(ckpt_path: str, metadata_path: str, out_path: str):
    print(f"Loading checkpoint: {ckpt_path}")
    ckpt = torch.load(ckpt_path, map_location="cpu")

    meta = {}
    if metadata_path and os.path.exists(metadata_path):
        with open(metadata_path, "r", encoding="utf-8") as f:
            meta = json.load(f)

    index_to_pitch = meta.get("index_to_pitch", ckpt.get("index_to_pitch", []))
    vocab_size = int(ckpt.get("vocab_size", len(index_to_pitch) or 0))
    if vocab_size <= 0:
        vocab_size = len(index_to_pitch)
    width = int(ckpt.get("width", ckpt.get("args", {}).get("width", 64)))
    sr    = int(ckpt.get("sr", meta.get("sr", 48000)))

    # Compute export window: ckpt may store it explicitly
    export_W = int(ckpt.get("export_window_samples", 0))
    if export_W <= 0:
        export_ms = float(ckpt.get("args", {}).get("export_ms", 8.0))
        export_W  = int(round(export_ms * sr / 1000.0))

    n_strings = 6

    print(f"  sr={sr}  vocab={vocab_size}  width={width}  export_window={export_W}")

    sd = ckpt["model_state"]

    # Detect prefix: could be "feat." or "conv." depending on train version
    def find_prefix(sd):
        for k in sd:
            if "conv" in k.lower() or "feat" in k.lower():
                return k.split(".")[0]
        return "feat"

    feat_key = find_prefix(sd)
    print(f"  Detected state_dict prefix: '{feat_key}'")

    # The 5 conv layers are at indices 0, 3, 6, 9, 12 in the Sequential
    # The 5 BN  layers are at indices 1, 4, 7, 10, 13
    conv_indices = [0, 3, 6, 9, 12]
    bn_indices   = [1, 4, 7, 10, 13]
    c_names      = ["l0", "l1", "l2", "l3", "l4"]

    lines = [
        "// Auto-generated by fix_weights_export.py – DO NOT EDIT",
        f"// OnsetNet weights: sr={sr} vocab={vocab_size} window={export_W} width={width}",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define ONSET_SR                 {sr}",
        f"#define ONSET_NOTE_VOCAB_SIZE    {vocab_size}",
        f"#define ONSET_WINDOW             {export_W}",
        f"#define ONSET_WIDTH              {width}",
        f"#define ONSET_N_STRINGS          {n_strings}",
        "",
        "static const char* onset_pitch_names[] = {",
    ]
    for p in (index_to_pitch[:vocab_size] if index_to_pitch else [str(i) for i in range(vocab_size)]):
        lines.append(f'    "{ascii_pitch(p)}",')
    lines += ["};", ""]

    # Export each conv + BN layer
    for i, (ci, bi, cname) in enumerate(zip(conv_indices, bn_indices, c_names)):
        wk = f"{feat_key}.{ci}.weight"
        if wk not in sd:
            # Try alternative prefix
            for alt in ["feat", "conv"]:
                wk2 = f"{alt}.{ci}.weight"
                if wk2 in sd:
                    feat_key = alt
                    wk = wk2
                    break

        if wk not in sd:
            raise KeyError(
                f"Cannot find '{feat_key}.{ci}.weight' in state_dict.\n"
                f"Available keys: {[k for k in sd.keys() if 'weight' in k]}")

        print(f"  Exporting {cname} (conv idx={ci}, bn idx={bi})")
        lines += arr(f"{cname}_conv_weight", sd[wk])

        # BN: weight, bias, running_mean, running_var
        for suffix, csfx in [("weight", "bn_weight"), ("bias", "bn_bias"),
                               ("running_mean", "bn_running_mean"),
                               ("running_var",  "bn_running_var")]:
            bk = f"{feat_key}.{bi}.{suffix}"
            if bk in sd:
                lines += arr(f"{cname}_{csfx}", sd[bk])
            else:
                print(f"  [WARN] missing {bk}")

    # Note head
    lines += arr("note_head_weight", sd["note_head.weight"])
    lines += arr("note_head_bias",   sd["note_head.bias"])

    # String head
    lines += arr("string_head_weight", sd["string_head.weight"])
    lines += arr("string_head_bias",   sd["string_head.bias"])

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\n[OK] Wrote {out_path}")
    size_kb = os.path.getsize(out_path) / 1024
    print(f"     File size: {size_kb:.1f} KB")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt",     required=True, help="Path to .pt checkpoint")
    ap.add_argument("--metadata", default="",    help="Path to metadata.json")
    ap.add_argument("--out",      default="Source/onset_weights.h",
                    help="Output path for the C header")
    args = ap.parse_args()
    export_full_header(args.ckpt, args.metadata or None, args.out)


if __name__ == "__main__":
    main()
